services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: litrater-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-litrater}
      POSTGRES_USER: ${POSTGRES_USER:-litrater_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-litrater_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - litrater-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-litrater_user} -d ${POSTGRES_DB:-litrater}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Keycloak Identity and Access Management
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: litrater-keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB:-litrater}?currentSchema=litrater_keycloak
      - KC_DB_USERNAME=${POSTGRES_USER:-litrater_user}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD:-litrater_password}
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    ports:
      - "${KEYCLOAK_PORT:-8080}:8080"
    networks:
      - litrater-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "timeout 10s bash -c '</dev/tcp/localhost/8080' || exit 1" ]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s
    volumes:
      - ./keycloak-init/litrater-realm.json:/opt/keycloak/data/import/litrater-realm.json
    command: [ "start-dev", "--import-realm" ]

  # Litrater Web Application
  litrater.presentation:
    image: ${DOCKER_REGISTRY-}litraterpresentation
    build:
      context: .
      dockerfile: src/Litrater.Presentation/Dockerfile
    container_name: litrater-api
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ConnectionStrings__Database=Host=postgres;Port=5432;Database=${POSTGRES_DB:-litrater};Username=${POSTGRES_USER:-litrater_user};Password=${POSTGRES_PASSWORD:-litrater_password}
      - Keycloak__Authority=${KEYCLOAK_AUTHORITY:-http://keycloak:8080/realms/litrater}
      - Keycloak__SwaggerAuthority=${KEYCLOAK_SWAGGER_AUTHORITY:-http://localhost:8080/realms/litrater}
      - Keycloak__Audience=${KEYCLOAK_AUDIENCE:-litrater-web-api}
      - Keycloak__RequireHttpsMetadata=${KEYCLOAK_REQUIRE_HTTPS:-false}
      - Serilog__MinimumLevel__Default=${SERILOG_MIN_LEVEL:-Information}
      - Serilog__MinimumLevel__Override__Microsoft=${SERILOG_MICROSOFT_LEVEL:-Warning}
      - Serilog__MinimumLevel__Override__System=${SERILOG_SYSTEM_LEVEL:-Warning}
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__1__Name=File
      - Serilog__WriteTo__1__Args__path=/app/logs/litrater-.log
      - Serilog__WriteTo__1__Args__rollingInterval=Day
      - Serilog__WriteTo__1__Args__retainedFileCountLimit=7
      - Serilog__WriteTo__2__Name=File
      - Serilog__WriteTo__2__Args__path=/app/logs/security-.log
      - Serilog__WriteTo__2__Args__rollingInterval=Day
      - Serilog__WriteTo__2__Args__retainedFileCountLimit=30
      - Serilog__WriteTo__2__Args__restrictedToMinimumLevel=Warning
      - Serilog__Enrich__0=FromLogContext
      - Serilog__Enrich__1=WithMachineName
      - Serilog__Enrich__2=WithThreadId
      - Serilog__Properties__Application=Litrater
    ports:
      - "${API_PORT:-5001}:8081"
    volumes:
      - litrater_logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - litrater-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://localhost:5001/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  litrater_logs:

networks:
  litrater-network:
    driver: bridge
